### ISSUE TITLE
Getting dashboard up & running

### ISSUE THREAD

**Issue by petervangennip** [phase2/pa11y-dashboard#5]
Hi,

I followed the readme.md instructions and everything goes well until actually getting the dashboard up and running.

When running `docker-compose run dashboard` I get this message:
Your application is running here: http://0.0.0.0:8080

Do I need to reroute this or something because http://0.0.0.0:8080 of http://localhost:8080 are not working.

**Comment by tjheffner** [comment]
that is the message from inside the container. if you're using the docker-compose from the readme, 0.0.0.0:8080 will be available outside of the container at www.pa11y.vm:8080 by default
